import Divider from "./components/Divider";
import Footer from "./components/Footer";

function App2() {



  return (
    <div className="border-4 border-red-500">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum expedita nostrum necessitatibus delectus quasi, explicabo quod dolores facilis possimus quisquam a vero deserunt, cumque in quidem eum amet architecto perspiciatis, sapiente recusandae placeat numquam. Fuga distinctio, harum odio vero consectetur consequatur eveniet neque quis a unde nisi autem, aspernatur deleniti aliquid? Minus unde alias quia sit minima veniam, deleniti repudiandae voluptates consequatur eligendi illum accusantium neque? Voluptatum nostrum nam a alias, officia necessitatibus ipsa, vero dolor autem accusamus blanditiis voluptates placeat eaque itaque nesciunt corporis atque eligendi debitis! Porro asperiores debitis ea animi officia perspiciatis? Eaque voluptas necessitatibus consequatur accusamus?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum expedita nostrum necessitatibus delectus quasi, explicabo quod dolores facilis possimus quisquam a vero deserunt, cumque in quidem eum amet architecto perspiciatis, sapiente recusandae placeat numquam. Fuga distinctio, harum odio vero consectetur consequatur eveniet neque quis a unde nisi autem, aspernatur deleniti aliquid? Minus unde alias quia sit minima veniam, deleniti repudiandae voluptates consequatur eligendi illum accusantium neque? Voluptatum nostrum nam a alias, officia necessitatibus ipsa, vero dolor autem accusamus blanditiis voluptates placeat eaque itaque nesciunt corporis atque eligendi debitis! Porro asperiores debitis ea animi officia perspiciatis? Eaque voluptas necessitatibus consequatur accusamus?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum expedita nostrum necessitatibus delectus quasi, explicabo quod dolores facilis possimus quisquam a vero deserunt, cumque in quidem eum amet architecto perspiciatis, sapiente recusandae placeat numquam. Fuga distinctio, harum odio vero consectetur consequatur eveniet neque quis a unde nisi autem, aspernatur deleniti aliquid? Minus unde alias quia sit minima veniam, deleniti repudiandae voluptates consequatur eligendi illum accusantium neque? Voluptatum nostrum nam a alias, officia necessitatibus ipsa, vero dolor autem accusamus blanditiis voluptates placeat eaque itaque nesciunt corporis atque eligendi debitis! Porro asperiores debitis ea animi officia perspiciatis? Eaque voluptas necessitatibus consequatur accusamus?
        
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum expedita nostrum necessitatibus delectus quasi, explicabo quod dolores facilis possimus quisquam a vero deserunt, cumque in quidem eum amet architecto perspiciatis, sapiente recusandae placeat numquam. Fuga distinctio, harum odio vero consectetur consequatur eveniet neque quis a unde nisi autem, aspernatur deleniti aliquid? Minus unde alias quia sit minima veniam, deleniti repudiandae voluptates consequatur eligendi illum accusantium neque? Voluptatum nostrum nam a alias, officia necessitatibus ipsa, vero dolor autem accusamus blanditiis voluptates placeat eaque itaque nesciunt corporis atque eligendi debitis! Porro asperiores debitis ea animi officia perspiciatis? Eaque voluptas necessitatibus consequatur accusamus?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum expedita nostrum necessitatibus delectus quasi, explicabo quod dolores facilis possimus quisquam a vero deserunt, cumque in quidem eum amet architecto perspiciatis, sapiente recusandae placeat numquam. Fuga distinctio, harum odio vero consectetur consequatur eveniet neque quis a unde nisi autem, aspernatur deleniti aliquid? Minus unde alias quia sit minima veniam, deleniti repudiandae voluptates consequatur eligendi illum accusantium neque? Voluptatum nostrum nam a alias, officia necessitatibus ipsa, vero dolor autem accusamus blanditiis voluptates placeat eaque itaque nesciunt corporis atque eligendi debitis! Porro asperiores debitis ea animi officia perspiciatis? Eaque voluptas necessitatibus consequatur accusamus?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum expedita nostrum necessitatibus delectus quasi, explicabo quod dolores facilis possimus quisquam a vero deserunt, cumque in quidem eum amet architecto perspiciatis, sapiente recusandae placeat numquam. Fuga distinctio, harum odio vero consectetur consequatur eveniet neque quis a unde nisi autem, aspernatur deleniti aliquid? Minus unde alias quia sit minima veniam, deleniti repudiandae voluptates consequatur eligendi illum accusantium neque? Voluptatum nostrum nam a alias, officia necessitatibus ipsa, vero dolor autem accusamus blanditiis voluptates placeat eaque itaque nesciunt corporis atque eligendi debitis! Porro asperiores debitis ea animi officia perspiciatis? Eaque voluptas necessitatibus consequatur accusamus?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum expedita nostrum necessitatibus delectus quasi, explicabo quod dolores facilis possimus quisquam a vero deserunt, cumque in quidem eum amet architecto perspiciatis, sapiente recusandae placeat numquam. Fuga distinctio, harum odio vero consectetur consequatur eveniet neque quis a unde nisi autem, aspernatur deleniti aliquid? Minus unde alias quia sit minima veniam, deleniti repudiandae voluptates consequatur eligendi illum accusantium neque? Voluptatum nostrum nam a alias, officia necessitatibus ipsa, vero dolor autem accusamus blanditiis voluptates placeat eaque itaque nesciunt corporis atque eligendi debitis! Porro asperiores debitis ea animi officia perspiciatis? Eaque voluptas necessitatibus consequatur accusamus?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum expedita nostrum necessitatibus delectus quasi, explicabo quod dolores facilis possimus quisquam a vero deserunt, cumque in quidem eum amet architecto perspiciatis, sapiente recusandae placeat numquam. Fuga distinctio, harum odio vero consectetur consequatur eveniet neque quis a unde nisi autem, aspernatur deleniti aliquid? Minus unde alias quia sit minima veniam, deleniti repudiandae voluptates consequatur eligendi illum accusantium neque? Voluptatum nostrum nam a alias, officia necessitatibus ipsa, vero dolor autem accusamus blanditiis voluptates placeat eaque itaque nesciunt corporis atque eligendi debitis! Porro asperiores debitis ea animi officia perspiciatis? Eaque voluptas necessitatibus consequatur accusamus?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum expedita nostrum necessitatibus delectus quasi, explicabo quod dolores facilis possimus quisquam a vero deserunt, cumque in quidem eum amet architecto perspiciatis, sapiente recusandae placeat numquam. Fuga distinctio, harum odio vero consectetur consequatur eveniet neque quis a unde nisi autem, aspernatur deleniti aliquid? Minus unde alias quia sit minima veniam, deleniti repudiandae voluptates consequatur eligendi illum accusantium neque? Voluptatum nostrum nam a alias, officia necessitatibus ipsa, vero dolor autem accusamus blanditiis voluptates placeat eaque itaque nesciunt corporis atque eligendi debitis! Porro asperiores debitis ea animi officia perspiciatis? Eaque voluptas necessitatibus consequatur accusamus?
    </div>
  )
}

export default App2;
